# Generated by Django 3.0.2 on 2020-06-05 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('AB', 'ALBA'), ('AR', 'ARAD'), ('AG', 'ARGES'), ('BC', 'BACAU'), ('BH', 'BIHOR'), ('BN', 'BISTRITA-NASAUD'), ('BT', 'BOTOSANI'), ('BV', 'BRASOV'), ('BR', 'BRAILA'), ('BZ', 'BUZAU'), ('CS', 'CARAS-SEVERIN'), ('CJ', 'CLUJ'), ('CT', 'CONSTANTA'), ('CV', 'COVASNA'), ('DB', 'DIMBOVITA'), ('DJ', 'DOLJ'), ('GL', 'GALATI'), ('GJ', 'GORJ'), ('HR', 'HARGHITA'), ('HD', 'HUNEDOARA'), ('IL', 'IALOMITA'), ('IS', 'IASI'), ('IF', 'ILFOV'), ('MM', 'MARAMURES'), ('MH', 'MEHEDINTI'), ('MS', 'MURES'), ('NT', 'NEAMT'), ('OT', 'OLT'), ('PH', 'PRAHOVA'), ('SM', 'SATU_MARE'), ('SJ', 'SALAJ'), ('SB', 'SIBIU'), ('SV', 'SUCEAVA'), ('TR', 'TELEORMAN'), ('TM', 'TIMIS'), ('TL', 'TULCEA'), ('VS', 'VASLUI'), ('VL', 'VILCEA'), ('VN', 'VRANCEA'), ('B', 'BUCURESTI'), ('CL', 'CALARASI'), ('GR', 'GIURGIU')], default='RO', max_length=3)),
                ('county', models.CharField(choices=[('AB', 'ALBA'), ('AR', 'ARAD'), ('AG', 'ARGES'), ('BC', 'BACAU'), ('BH', 'BIHOR'), ('BN', 'BISTRITA-NASAUD'), ('BT', 'BOTOSANI'), ('BV', 'BRASOV'), ('BR', 'BRAILA'), ('BZ', 'BUZAU'), ('CS', 'CARAS-SEVERIN'), ('CJ', 'CLUJ'), ('CT', 'CONSTANTA'), ('CV', 'COVASNA'), ('DB', 'DIMBOVITA'), ('DJ', 'DOLJ'), ('GL', 'GALATI'), ('GJ', 'GORJ'), ('HR', 'HARGHITA'), ('HD', 'HUNEDOARA'), ('IL', 'IALOMITA'), ('IS', 'IASI'), ('IF', 'ILFOV'), ('MM', 'MARAMURES'), ('MH', 'MEHEDINTI'), ('MS', 'MURES'), ('NT', 'NEAMT'), ('OT', 'OLT'), ('PH', 'PRAHOVA'), ('SM', 'SATU_MARE'), ('SJ', 'SALAJ'), ('SB', 'SIBIU'), ('SV', 'SUCEAVA'), ('TR', 'TELEORMAN'), ('TM', 'TIMIS'), ('TL', 'TULCEA'), ('VS', 'VASLUI'), ('VL', 'VILCEA'), ('VN', 'VRANCEA'), ('B', 'BUCURESTI'), ('CL', 'CALARASI'), ('GR', 'GIURGIU')], default='B', max_length=2)),
                ('city', models.CharField(default='Bucuresti', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('phone_no', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('women_services', models.BooleanField(default=False)),
                ('men_services', models.BooleanField(default=False)),
                ('kids_services', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beautinator.Location')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=15)),
                ('birthday', models.DateField(blank=True)),
                ('gender', models.CharField(choices=[('F', 'Feminin'), ('M', 'Masculin'), ('N', 'Niciuna / Prefer sa nu spun')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FH', 'Coafor'), ('BE', 'Cosmetica'), ('MH', 'Frizerie'), ('MP', 'Manichiura')], max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('price', models.FloatField()),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=900))),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautinator.Salon')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=900))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautinator.User')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautinator.Salon')),
                ('service', models.ForeignKey(limit_choices_to={'salon': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautinator.Salon')}, on_delete=django.db.models.deletion.CASCADE, to='beautinator.Service')),
            ],
        ),
    ]
