# Generated by Django 3.0.2 on 2020-06-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautinator', '0002_auto_20200605_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
