# Generated by Django 3.0.2 on 2020-06-05 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautinator', '0003_auto_20200605_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='salon',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautinator.Service'),
        ),
    ]
