# Generated by Django 3.0.2 on 2020-06-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautinator', '0008_auto_20200613_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
    ]
