# Generated by Django 3.0.6 on 2020-06-13 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautinator', '0009_remove_appointment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
    ]
