# Generated by Django 3.0.2 on 2020-06-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautinator', '0011_auto_20200613_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='start_date',
            new_name='date',
        ),
    ]
