# Generated by Django 3.0.6 on 2020-06-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautinator', '0010_appointment_duration'),
        ('beautinator', '0011_auto_20200613_2129'),
    ]

    operations = [
    ]
