# Generated by Django 3.0.6 on 2020-06-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautinator', '0012_merge_20200614_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
    ]
