# Generated by Django 3.0.6 on 2020-06-14 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautinator', '0013_remove_appointment_duration'),
        ('beautinator', '0013_auto_20200614_2102'),
    ]

    operations = [
    ]
