# Generated by Django 3.0.6 on 2020-06-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautinator', '0014_salon_logo'),
        ('beautinator', '0014_merge_20200615_0116'),
    ]

    operations = [
    ]
