# Generated by Django 3.0.2 on 2020-06-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautinator', '0017_auto_20200615_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
